name = "jaiclubpro"
compatibility_date = "2024-08-01"
pages_build_output_dir = "."

# Cloudflare Pages Custom Domain Worker config
# Run locally using: npx wrangler pages dev .

# Default environment variables for the worker

[vars]
JAICLUBPRO_PASSCODE = "aryan8384"
